"""Centralized constants and configuration for the whole package.

Single source of truth: sample window, instrument definition, data-source
endpoints, and WRDS references live here and are imported elsewhere. No magic
number or endpoint string is repeated in another module.
"""
from __future__ import annotations

# ----- Determinism -----
RANDOM_SEED: int = 20240501  # program restart month; fixed for all randomness

# ----- Sample window -----
SAMPLE_START: str = "2024-05-01"   # regular buyback program restart
CORE_END: str = "2025-12-31"       # last date fully covered by CRSP daily
STRESS_END: str = "2026-09-30"     # extends through the 2026 out-of-sample stress test

# ----- Instrument Z_i: heavy tax-inflow maturity months -----
TAX_INFLOW_MONTHS: tuple[int, ...] = (4, 6, 9, 12)  # April, June, September, December

# ----- Public data sources (no credentials) -----
FISCALDATA_BASE: str = (
    "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/od"
)
FISCALDATA_DATASETS: dict[str, str] = {
    "buyback_operations": "buybacks_operations",
    "buyback_security_details": "buybacks_security_details",
    "auctions": "auctions_query",
}
TREASURYDIRECT_AUCTIONED: str = "https://www.treasurydirect.gov/TA_WS/securities/auctioned"
PAR_YIELD_CSV: str = (
    "https://home.treasury.gov/resource-center/data-chart-center/interest-rates/"
    "daily-treasury-rates.csv/{year}/all"
    "?type=daily_treasury_yield_curve&field_tdr_date_value={year}&_format=csv"
)

# ----- WRDS / CRSP (licensed; regenerated by a subscriber) -----
WRDS_LIBRARY: str = "crsp_a_treasuries"
WRDS_TABLES: dict[str, str] = {
    "daily": "tfz_dly",   # per-CUSIP daily bid/ask, price, yield, duration, outstanding
    "issues": "tfz_iss",  # CUSIP crosswalk: tcusip <-> kytreasno, maturity, coupon
}
