"""Centralized constants and configuration for the whole package.

Single source of truth for the values shared across layers: the determinism
seed, the sample window, the calendar conversions used to express day counts in
years, the instrument definition, and the references of the licensed CRSP tables
that a subscriber regenerates. No magic number and no endpoint string is
repeated in another module; every consumer imports from here.
"""
from __future__ import annotations

# ----- Determinism -----
RANDOM_SEED: int = 20240501  # program restart month; fixed for all randomness

# ----- Sample window -----
SAMPLE_START: str = "2024-05-01"   # regular buyback program restart
CORE_END: str = "2025-12-31"       # last date fully covered by CRSP daily
WINDOW_END: str = "2026-09-30"     # last date of the full program window

# ----- Calendar conversions (day counts to years) -----
DAYS_PER_YEAR: float = 365.25   # mean Gregorian year
MONTHS_PER_YEAR: float = 12.0
DAYS_PER_WEEK: float = 7.0

# ----- Instrument Z_i: heavy tax-inflow maturity months -----
TAX_INFLOW_MONTHS: tuple[int, ...] = (4, 6, 9, 12)  # April, June, September, December

# ----- Public data sources (no credentials) -----
# Read by the acquisition step that regenerates the shipped parquet files in
# data/ (see data/README.md); the reproduction itself reads only those files.
FISCALDATA_BASE: str = (
    "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/od"
)
FISCALDATA_DATASETS: dict[str, str] = {
    "buyback_operations": "buybacks_operations",
    "buyback_security_details": "buybacks_security_details",
    "auctions": "auctions_query",
}
PAR_YIELD_CSV: str = (
    "https://home.treasury.gov/resource-center/data-chart-center/interest-rates/"
    "daily-treasury-rates.csv/{year}/all"
    "?type=daily_treasury_yield_curve&field_tdr_date_value={year}&_format=csv"
)

# ----- WRDS / CRSP (licensed; regenerated by a subscriber) -----
# Library and table names a WRDS subscriber needs to rebuild data/crsp/
# (see data/crsp/README.md). CORE_END bounds that pull.
WRDS_LIBRARY: str = "crsp_a_treasuries"
WRDS_TABLES: dict[str, str] = {
    "daily": "tfz_dly",   # per-CUSIP daily bid/ask, price, yield, duration, outstanding
    "issues": "tfz_iss",  # CUSIP crosswalk: tcusip <-> kytreasno, maturity, coupon
}
